import express from "express";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config();

const app = express();

app.use(cors());
app.use(express.json());

const PORT = 5000;

const OLLAMA_URL = "http://localhost:11434/api/generate";

const MODEL = process.env.OLLAMA_MODEL || "llama3.2";

const GUIDEAI_SYSTEM_PROMPT = `
You are GuideAI, an AI assistant designed to provide clear, accessible,
and user-controlled responses.

GuideAI is designed around Human-AI Interaction principles.

Your goals are:

1. Use clear and simple language.
2. Avoid unnecessary technical terminology.
3. Organize information so it is easy to understand.
4. Be transparent when information may be uncertain or incomplete.
5. Never pretend that you verified information from a source if you did not.
6. Do not fabricate government websites, laws, policies, statistics, or sources.
7. Remind users when information should be independently verified.
8. Make it clear that responses are AI-generated.
9. Support the user's ability to review, edit, question, or reject a response.
10. Do not treat your response as automatically correct.

GuideAI has three important refinement options:

SIMPLIFY:
Rewrite the response using easier language while keeping the important
information.

SUMMARIZE:
Shorten the response and keep only the most important information.

EXPLAIN:
Provide additional detail or clarification about the response.

These options should have clearly different purposes.

If a user asks for a response involving important decisions, legal information,
government requirements, health, finances, safety, or other high-impact topics,
clearly explain that the user should verify important information using an
appropriate authoritative source.

GuideAI follows a Human-in-the-Loop approach. The human user remains
responsible for reviewing and deciding whether to use the response.
`;

app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    provider: "Ollama",
    model: MODEL,
  });
});

app.post("/api/guideai", async (req, res) => {
  try {
    const {
      message,
      mode = "normal",
      existingResponse = "",
      feedback = "",
    } = req.body;

    if (!message || typeof message !== "string") {
      return res.status(400).json({
        error: "A message is required.",
      });
    }

    let modeInstruction = "";

    if (mode === "simplify") {
      modeInstruction = `
Rewrite the response using easier, plain-language wording.
Keep the important facts and meaning.
Do not remove important information just to make the response shorter.
`;
    }

    if (mode === "summarize") {
      modeInstruction = `
Summarize the response.
Keep the most important information and remove unnecessary detail.
Use short paragraphs or bullet points when helpful.
`;
    }

    if (mode === "explain") {
      modeInstruction = `
Explain the response in more detail.
Clarify concepts that may be confusing.
Use examples when appropriate.
`;
    }

    const prompt = `
${GUIDEAI_SYSTEM_PROMPT}

Current mode:
${mode}

${modeInstruction}

User message:
${message}

${existingResponse
  ? `Existing response to refine:
${existingResponse}`
  : ""}

${feedback
  ? `User feedback:
${feedback}`
  : ""}

Provide only the response that should be shown to the user.
`;

    const ollamaResponse = await fetch(OLLAMA_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODEL,
        prompt,
        stream: false,
        options: {
          temperature: 0.3,
        },
      }),
    });

    if (!ollamaResponse.ok) {
      const errorText = await ollamaResponse.text();

      console.error("Ollama error:", errorText);

      return res.status(500).json({
        error:
          "GuideAI could not communicate with Ollama. Make sure Ollama is running.",
      });
    }

    const data = await ollamaResponse.json();

    res.json({
      reply: data.response,
      mode,
      aiGenerated: true,
      provider: "Ollama",

      reviewNote:
        "This response was generated by a local AI model and should be reviewed before use.",
    });
  } catch (error) {
    console.error("GuideAI server error:", error);

    res.status(500).json({
      error:
        "GuideAI encountered an unexpected error. Check that Ollama and the GuideAI server are running.",
    });
  }
});

app.listen(PORT, () => {
  console.log(`GuideAI server running at http://localhost:${PORT}`);
  console.log(`Using Ollama model: ${MODEL}`);
});